<?php

namespace OOP\App\TemplateMethod\StarbuzCoffee;

class CoffeeWithHook extends Drink
{

    public function brew(): void
    {
        echo "Brewing the coffee...\n";
    }

    public function addCondiments(): void
    {
        echo "Adding milk and sugar...\n";
    }

    protected function ifCondiments(): bool
    {
        echo "Do you want milk and sugar?\n";
        return parent::ifCondiments(); // TODO: Change the autogenerated stub
    }
}
