<?php

namespace OOP\App\TemplateMethod\StarbuzCoffee;

class TeaWithHook extends Drink
{

    public function brew(): void
    {
        echo "Brewing the tea...\n";
    }

    public function addCondiments(): void
    {
        echo "Adding a lemon...\n";
    }

    protected function ifCondiments(): bool
    {
        echo "Do you want lemon?\n";
        return parent::ifCondiments(); // TODO: Change the autogenerated stub
    }
}
